Repository xitu/blockchain-miner, pull requests merged in 2018-09, with the labels that each got.

#5 Translated what-is-ethereum.md
  article/0001/what-is-ethereum.md
Labels: enhancement, 正在校对

#4 EthList：众包维护的以太坊阅读清单
  ethlist.md
Labels: 标注, 正在校对

#6 ELI5：用简单的语言给小白解释什么是以太坊？
  article/0001/eli5-what-is-ethereum.md
Labels: Ethereum, 标注, 正在校对
